### ISSUE TITLE
Choice to change videoplayer

### ISSUE THREAD

**Issue by Zabooby** [ThaUnknown/miru#128]
I saw on the faq page that miru uses the browsers built in video player, is there any plans to add mpv or give us the choice to use an external player without leaving the app?

**Comment by ThaUnknown** [comment]
no, it's not viable, and any form of bindings wouldn't be maintainable long-term from my point of view, I don't want the app to open a 3rd party player, that's just stupid, if anything the player would have to be embedded in the app, and I'm not aware of any possibilities of doing so. There's a MPV embedded player for electron, but afaik that relies on flash, and the extensions api is slowly being deprecated, so that's a no from me. I also don't see a need for a 3rd party player here, the current one does [almost] everything [except a few codecs which I plan on fixing]

also. invalid issue template, fill out the issue template correctly

**Comment by Zabooby** [comment]
> Any plans to add option to add custom shaders like https://github.com/bloc97/Anime4K?

**Comment by ThaUnknown** [comment]
> > Any plans to add option to add custom shaders like https://github.com/bloc97/Anime4K?

the community would kill me, so no.

**Comment by Zabooby** [comment]
> > > Any plans to add option to add custom shaders like https://github.com/bloc97/Anime4K?
> 
> the community would kill me, so no.

Lmao maybe that was a trick question. 
Well thanks for the super fast replies I'll still try it out, it definitely looks promising. 
Keep up the good work!

**Comment by ThaUnknown** [comment]
yeah

all your suggestions are purely "preference" and dont actually have any merit, it might have been fine for other apps, but as this is FOSS and i already have little time as it is i dont plan on adding support for things that dont actually improve anything just because people prefer something else
