### ISSUE TITLE
Show video download/buffer status

### ISSUE THREAD

**Issue by R3D4CTED** [ThaUnknown/miru#129]
It would be great if there were a preview showing how far the video has buffered, similar to YouTube. Something similar to this:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/28143681/162420543-f07ac8dd-5350-4fc2-a418-877e685a0e7f.png">

**Comment by ThaUnknown** [comment]
> It would be great if there were a preview showing how far the video has buffered, similar to YouTube. Something similar to this: <img alt="image" width="953" src="https://user-images.githubusercontent.com/28143681/162420543-f07ac8dd-5350-4fc2-a418-877e685a0e7f.png">

I've thought about this, but it would be nothing more than a lie, I cannot predict how much a video is buffered, mainly because of variable bitrate, I can easily tell which parts of a file are downloaded, but I can't easily check what timestamp that part of the file corresponds to.

If you know how to solve this, write.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/ee8bd6d23721e89d01d6608af9a75ad255801dcd
cba profiling it, lets hope it doesn't introduce too much overhead lol
