### ISSUE TITLE
Setting to Enable/Disable Discord Rich Presence

### ISSUE THREAD

**Issue by Currential** [ThaUnknown/miru#157]
**Is your feature request related to a problem? Please describe.**
I would like to disable discord rich presence when I'm using Miru.

**Describe the solution you'd like**
An option in the settings menu where you can toggle the discord rich presence ON/OFF.

**Additional context**
N/A

**Comment by ThaUnknown** [comment]
just disable it ic discord settings!

**Comment by Currential** [comment]
The issue is that I want Miru specifically to be hidden or not shown in my activity. There is currently no option that I am aware of where I can disable the activity of a specific application on Discord. You can only globally turn off discord rich presence entirely.

**Comment by ThaUnknown** [comment]
you could go invisible :p
i know this is a potential issue but idk if i really want to fix it, i might do it for ecchi shows, but idk if this is a serious problem

**Comment by Currential** [comment]
Yeah, I guess going invisible is a valid method. Just thought I'd let you know, and if you could implement it if you ever get around to it. It isn't something urgent, mainly a QOL feature. I'll close the issue with this.

**Comment by ThaUnknown** [comment]
I'll leave this open, for potential conversations, as of now i don't see the point but someone could convince me otherwise

**Comment by ThaUnknown** [comment]
stale

**Comment by LeinadUchiha** [comment]
Good, I know it is not a very serious problem as you mentioned above, but if it is something that would greatly improve the quality of life experience, mostly for privacy issues, as you said in the case of ecchi anime that can cause misunderstandings between friends or family who have been added to discord either because you really wanted to see that kind of anime or by some mistake because just by clicking on a chapter and then open the description, and it appears as if you were watching that anime, also stays even when you close the program, there is also the issue that in some cases one wants to see an anime of his childhood and can be frowned upon by people from other environments such as work or study groups in discord, as I mentioned at the beginning more than anything is for privacy issue, to finish I wanted to say that I do not speak English and use a translator to leave this comment I hope you have been able to understand well what I meant.

**Comment by ThaUnknown** [comment]
again you can just go invisible on discord if its that big of an issue or disable rich pressence in discord settings, and if your friends judge you for what you watch, then I'm sorry to say they are definitely not your friends and I recommend you find a different group of people to hang out with before you get tripped up, the issue about it staying there on close is I think a discord bug, not Miru bug

it's not that making an option to turn off rich presence is difficult, it's that I deem it very unnecessary in the first place

**Comment by LeinadUchiha** [comment]
Thank you for taking the time to read my request. I understand that the rich presence on discord may not be a concern for you, but for some users it is an important privacy issue. I want to point out that the scenarios I mentioned in my comment are possible situations discussed by the user community. I would like to make a suggestion to you with the greatest possible respect and kindness: what if you would consider including an option to disable rich presence in a future update? Not only would it improve the user experience for those who need it, but it would also protect users' privacy. We all want to feel safe and comfortable online, and this option would help greatly in that regard. Thank you for taking my request into consideration and for all the work you do in developing this application. I look forward to your consideration of this suggestion.

**Comment by RiTk2** [comment]
if u run discord as an Administrator, it won't detect Miru, unless u run Miru as Administrator

**Comment by ThaUnknown** [comment]
yes, this is normal behavior for discord, I personally advice against running discord and especially miru as admin

**Comment by RiTk2** [comment]
> yes, this is normal behavior for discord, I personally advice against running discord and especially miru as admin

oh thanks but yeah sometimes u need to run discord as admin to use keybinds when u in game so yeah...

**Comment by QuiteAFancyEmerald** [comment]
I think this would be a good feature to implement because it gets very tedious having to go invisible every time I open Miru. It doesn't really matter about friends rather malicious people on Discord when either in large Discord servers or just active on Discord. Showcasing something like this in your status (especially with the term torrenting and all) is pretty close to violating TOS. Most applications that have some sort of RPC have an option to disable it via the app. It just contains a lot of extra steps each time this is the only open-source client (I use quite a lot) where I need to be aware of this each time I open it. I'm sure this is a similar case for others
