### ISSUE TITLE
Add Scoring option

### ISSUE THREAD

**Issue by rentela** [ThaUnknown/miru#160]
**Is your feature request related to a problem? Please describe.**
Finishing a series i would like to set my score like in Anilist or MAL

**Describe the solution you'd like**
It would be nice to have some system to score the series. Something like a dropdown box to choose from 1 to 10.

**Additional context**
Something like the scoring system on Taiga would be perfect
![image](https://user-images.githubusercontent.com/59053926/164522736-b22bb098-ab2d-4050-a428-7dfce513b584.png)

**Comment by ThaUnknown** [comment]
I'm very torn on this, I partially don't want to implement this, even tho it's a good suggestion.

The main reason is this app is used by normies, which might not understand that the scoring system is actually not hosted by me, and instead anilist, and they might use the scoring system to voice their complaints about playback, torrenting, availability etc, which might end up hurting anilist, when they aren't the ones at fault. 

I can't think of any way of presenting the scoring system which would detatch the user's perspective of the score, from their experience watching it, as thing such as crashes, errors, bugs etc in the app might influence the score and give it an unfair rating.

If you have any opinions/ideas/suggestions about this topic, please comment

**Comment by rentela** [comment]
I understand your point of view about the normies but maybe implement the scoring and only display that field to the ones that have login on anilist.
The users that have anilist and use it in the app for the progress and the rest, will understand that the scoring system is related to the anilist rather that their personal experience with the app i think. 
Anyway i understand your point of view and look forward to hearing more opinions/ideas/suggestions about this topic.

**Comment by ThaUnknown** [comment]
you can only score anime when logged into anilist, I thought that was a duh', I'm considering having the field grayed out when not logged in, and also when the anime isn't finished/dropped, meaning you can't rate an anime when not watching it, or still watching it, and as I won't implement a "drop anime" functionality, it should be safe from people dropping it just because they had trouble watching it on the app, however this still introduces a bias, as only potentially more positive shows will be able to be rated.

**Comment by Felixnightshade** [comment]
Only rating anime when logged into anilist isn't a duh', as it is common for similar programs to have local ratings (e.g. Plex). 
Beyond that, one solution to bad ratings due to app/torrent issues could be having a second prompt for why their rating is bad, with quality issues being one of the options. Any ratings where those app specific issues are ticked can simply not be submitted to anilist and instead be stored locally. 
Another solution could be to have two rating sections. One score for the anime itself and one for the viewing experience on the app. The second rating could be used for additional features as well.

**Comment by ThaUnknown** [comment]
> Only rating anime when logged into anilist isn't a duh', as it is common for similar programs to have local ratings (e.g. Plex). Beyond that, one solution to bad ratings due to app/torrent issues could be having a second prompt for why their rating is bad, with quality issues being one of the options. Any ratings where those app specific issues are ticked can simply not be submitted to anilist and instead be stored locally. Another solution could be to have two rating sections. One score for the anime itself and one for the viewing experience on the app. The second rating could be used for additional features as well.

while this is a very sound, and logical solution, the UI/UX for it would be very complex, the way these kind of components have to be designed, is for people who can't speak any language to be able to use them

this makes it very complex, and off-putting when they have to click tru 3 layers of confirmations just to submit a score, and it's kinda bad for the flow of the app I'm trying to create. This is ESPECIALLY an issue, when some1 ragequits the anime because of poor playback/buffering/issues and then they have to go tru a confirmation "did you like the viewing experience". If they are already fuming it's probably the worst thing you can do for that kind of person, I doubt they'd ever return

**Comment by Felixnightshade** [comment]
I guess it comes down to how feature-rich you want the app to be and the intended user base. I would personally like to be able to make note of anime that had shit seeding/quality, but if you're trying to target people that shouldn't even be torrenting in the first place, then I suppose that limits the options.
Perhaps dead simple local ratings would be a good solution then?
