### ISSUE TITLE
[Feature Request]: Nyaa Sukebei Support

### ISSUE THREAD

**Issue by GlitchChan** [ThaUnknown/miru#259]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Adding support for browsing and playing from Sukebei which is Nyaa's nsfw site

### Proposed Solution

Possibly making the app check both Nyaa and Sukebei when searching for a torrent.

**Comment by Y3flamex** [comment]
AND ALSO ADD A TOGGLE i don't wanna be sitting in my living room searching for a family friendly anime to watch then BOOM anime titties splashed everywhere and i ruin thanksgiving a third time

**Comment by ThaUnknown** [comment]
I already tried implementing this one and it simply doesn't work, the overlap between AniList hentai and sukebei hentai isn't there, additionally sukebei doesn't really have subbed only categories like main does, so that'd become an issue too, overall from my testing I couldn't write anything that'd autodetect hentai on sukebei, and the shit that was detected was available on main too
