### ISSUE TITLE
Stremio features/Torrent options

### ISSUE THREAD

**Issue by randoomdude** [ThaUnknown/miru#289]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

I don't know if you've ever used stremio, but Miru seems pretty similar in that it uses torrents to stream video files. Problem is, especially with older series, sometimes it will have the wrong torrent link, and it doesn't give you options or details on the torrent file you are using so you just end up stuck with it. Also options to access episode list from the Now Playing window or drop torrents to play would be a nice feature to have, the base is good I think but still feels incomplete with lack of features.

Also having a way to mark anime on the home page with color tags or something like Anichart has (green, yellow, red) for new/old shows would be cool I think

### Proposed Solution

Adding features

**Comment by ThaUnknown** [comment]
miru is miru, stremio is stremio, the idea behind miru is that its a streaming site-like app, which doesn't expose torrents that much so the user doesnt have to worry about them, it just works.

if you want to pick specific torrents because miru picked something incorrectly you can disable auto-play torrents in RSS settings

file list wont happen, as again the user shouldnt need to worry about that, if you are playing a batch and want to pick a file, simply go to the currently playing media [sidebar button] and select an episode from the list, if the current batch has such an episode it will play it instead of downloading a new torrent, if it doesn't it will look for a new torrent and play it, a filelist isn't useful here as if this episode lookup fails, miru wouldnt play that file correctly anyways
