### ISSUE TITLE
[Bug]: Temp folder not being cleared correctly

### ISSUE THREAD

**Issue by SoaringGecko** [ThaUnknown/miru#312]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.3.4

### What operating system version are you using?

Windows

### Expected Behavior

The Temp folder is cleared on software close/episode switch

### Actual Behavior

Earlier today I realized that about 20+ GB of space on my SSD was suddenly gone and it was because the Temp folder for Miru wasn't cleared for a series. It also had episodes in there that I am still yet to watch which is a little strange.

**Comment by ThaUnknown** [comment]
this is likely because miru picked a batch to play, which is a collection of multiple episodes, those are usually better quality and better seeded than individual episodes, so that decision is correct

Miru will not clear data on app close, because if you re-open it, it will start downloading that 20GB again, which is counter-intuitive and wasteful

you can chance the tmp storage folder in settings if you don't want to waste space on ur SSD, and that is recommended, as the data access doesn't need to be fast, as the video buffers ahead for better UX anyways

**Comment by SoaringGecko** [comment]
I agree that it's kind of counter-intuitive to delete on close, but I feel like that wouldn't be a bad thing to have as a toggle for those that would want it. Kind of like how some people enable clearing cache on close for Firefox.

**Comment by ThaUnknown** [comment]
unfortunately for you this isnt firefox, the data isn't statically server, doing this would hurt the torrent swarm and reduce the amt of data you are capable of seeding while watching, hurting the data distribution model of the app

**Comment by SoaringGecko** [comment]
Interesting, I never really thought about that as a potential problem.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/issues/314
