### ISSUE TITLE
[Feature Request]: Subtitle, My Library, Back button, Series list

### ISSUE THREAD

**Issue by IASAH** [ThaUnknown/miru#321]
### Preflight checklist

- [x] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [ ] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

First I want to say I just discovered this app and it's what I've been looking for, Great job Thank you.
Now you know what I'm about to say is something to help this app be one of the best.

* Subtitles, My language is listed but it's not showing in any anime when watching.
* My Library, we all have our favorite anime that either we are watching or on the waiting list.
* Back button, The 1st time I used the app I broke it because I kept closing it to go back to the main menu.
* Series List, Alot of time we watch multiple episodes of the same at once.

### Proposed Solution

Subtitles
You can add better subtitle sources or give us the ability to add sources to the subtitle both at settings or per episode so we can choose better sources for our languages like "Arabic".

My library.
You can add a separate section at the sidebar that has only my list of animes so I can go there and catch up on what I have left.

Back button, 
I believe a back button will be a great help for newbies like me.

Series List,
Wouldn't it be nice if we had a drag list from the side or bottom to choose another episode of the same series?

finally, I love to see this app become great A lot of those suggestions came from using 'Stremio' I think it good stable app but most of its support goes to Hollywood movies and serieses but we can learn a couple of things from its implementation.

**Comment by ThaUnknown** [comment]
this isnt how gh issues work, each issue should be listed separately, anyways, not an issue since these are all addressed
- you missed the "What Subtitle Language To Automatically Select, If Not Found Defaults To English", miru only does english subs, if it finds others thats a cherry on top, but there's no way to reliably find torrents in other languages, so this is not gonna happen, you can manually pick torrents and look for multi subs yourself
- this... already exists on the home screen under "your list"
- there's no need for a back button, miru's navigation is one dimensional, just press the home button on the left and that's your back button
- yes, on the side there's a currently playing media button
