### ISSUE TITLE
[Feature Request]: Smart Seeding

### ISSUE THREAD

**Issue by MidnightKittenCat** [ThaUnknown/miru#362]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

The problem is that, after an episode of a TV show or series is finished seeding or playing, there is often a delay before the next episode starts. This delay can be frustrating for viewers, especially when they are binge-watching a series and want a seamless viewing experience. The feature request aims to address this issue by automatically seeding the next episode in a series once the previous one is done seeding or playing, provided that there is another episode available in the series.

### Proposed Solution

Would be cool to have it so after an episode is done being seeded, that it starts seeding the next episode so we don't have to wait for it to get started(given that there is another episode afterwards, hence eliminating the delay if we decide to keep it on)

**Comment by EnergoStalin** [comment]
You can pick batch release(if there's any) for that purpose it download whole season and you get seamless experience when switching between episodes. Otherwise you will be doomed to pick torrent for every/(one ahead) episode? Or might get "unwanted torrents"(first matching) to be played. This is the only solution i can see. In first case you will be interrupted anyway in second it might really work seamlessly until you get your subs missed(not actually an issue for english). But it definitely can benefit in case of slow internet/peering. So yes.

Personally i have 10mb/s internet and waiting for me is around 10 or less seconds to start playing so not problem for me. Got right amount of time to think about previous episode.

**Comment by ThaUnknown** [comment]
If you're binge watching like this, then I greatly recommend batches, the delay is also very small, roughly 10-15 seconds at most, so I don't see it as a major issue, for torrents, this low of a latency for search, find, download and play is pretty much unheard of

I shudder at the decision graph and heuristics for this "smart seeding" you're suggesting, and in many cases it will cause more issues than actually help, adding unnecessary complexity

this will have to be a no, too much work, little gains, a lot of possible issues
