### ISSUE TITLE
[Feature Request]: Allow yourself to become a seeder

### ISSUE THREAD

**Issue by DTEXETD** [ThaUnknown/miru#365]
### Problem Description

Miru does'nt allow for torrent seeding after download of the full torrent

### Proposed Solution

Set an option to enable seeding in the torrent settings ("persist files" should obviously be enabled by force) and upload limit set by the user

**Comment by EnergoStalin** [comment]
I think it can be achieved using miru with regular torrent software which support watching folders for torrent files. But for that we need miru store torrent files somewhere first which I suggested as part of this feature https://github.com/ThaUnknown/miru/issues/361#issuecomment-1780233144. So in that case after miru finished playback prioritized download it will place torrent in folder where it can be picked by regular torrent software and seeded without problems in background even when miru closed. Because for now miru only seeding last torrent so it's not suitable for long term seeding. In my knowledge about current infrastructure and obvious lack of @ThaUnknown time it's not easy to turn miru in stable full featured torrent client with background seeding nor worth doing so. So i'd like to see more integration with external tooling as an option here.

The possible drawbacks is it's will be harder to control brandwith among miru and other torrent clients but it depends on how it will be implemented and which client is used.

I wont suggest disabling miru seeding functionality entirely because not anyone will use external torrent client + miru setup. And we need an acceptable alternative.

**Comment by ThaUnknown** [comment]
while this is possible, the simplest answer is no.

by thinking if you can you didn't think if you should, Miru isn't a torrent client like qbit, or a media library manager like plex or jf, which both usually run on hardware dedicated for it

Miru is designed to replace streaming sites, and it's functionality mimics them closely, it's meant to run on hardware which potentially doesn't have any space, or has insanely poor performance, which is where the "1 torrent limit" stems from

adding this is trivial, but I won't do it as managing resources [CPU, RAM, storage] becomes INSANELY hard for this, as Miru relies on real-time updates for user feedback, it's shit you wouldn't care when running qbit or plex, so when all of a sudden "anime doesnt load when I look up for it" because you're maxxing ur internet out by seeding, or "miru makes my whole pc unresponsive" because its maxing out ur storage, people's opinions of this software will degrade

persist files is there for users who have the storage, and don't want to rape the torrent swarm by re-downloading torrents they watch

While "Miru as a media managment library" just like JF is on my milestone list, it's much more complex than this, so I'll be closing this
