### ISSUE TITLE
[Bug]: Large torrent detected, torrent too big.

### ISSUE THREAD

**Issue by KataneeSan** [ThaUnknown/miru#397]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v4.5.8

### What operating system version are you using?

Linux

### Actual Behavior

Upon opening the app or starting a stream this warning and error pops up. After some time, usually 5-10 minutes there is another error about there being no space left and the stream stops. After that the app needs restarting. Of course there is enough space on the drive, I have checked. The default folder is /tmp and changing it to another one didn't fix it.
The error pops up on EndeavourOS and Garuda, both Arch-based systems.

### Screenshots

![Screenshot from 2023-12-24 21-10-57](https://github.com/ThaUnknown/miru/assets/154685404/cb936860-b07c-4ebb-bd5b-fc179d1bc1d8)
![Screenshot from 2023-12-24 21-12-08](https://github.com/ThaUnknown/miru/assets/154685404/ca2b1eea-72b5-4539-a3bd-1b82b4d45aa7)

**Comment by ThaUnknown** [comment]
how did you install miru?

**Comment by KataneeSan** [comment]
I installed miru as an aur package, appimage and through the gnome-software app. All of which had the same problem unfortunately. I'm not sure how to check the total size of the torrent, but I have 1.5TiB available on my PC.
Thank you

**Comment by KataneeSan** [comment]
> how did you install miru? whats the size of the torrent you're trying to download? how much space do you have on your drive?

I installed miru as an aur package, appimage and through the gnome-software app. All of which had the same problem unfortunately. I'm not sure how to check the total size of the torrent, but I have 1.5TiB available on my PC.
Thank you

**Comment by ThaUnknown** [comment]
this happens because Miru will resume downloads where they left off for the last watched torrent, which means it needs to re-scan files, which on slow HDD's might take a while if its a massive torrent

from my testing I don't think this is an issue with Miru, and since you're using linux I'm not willing to offer much help, as there are as many unique errors caused by linux configurations as there are linux users and I don't have the time to help all of them.

here's a list of potential issues:
- you picked an anime that has only one very seeded torrents that's massive, [HxH, FMA, One Piece], you can verify this by disabling auto-select torrents
- your linux config limits the available space to be used by the application in the /tmp folder or overall
- your linux config missreports available space
