### ISSUE TITLE
[Feature Request]: Keyword/Tag Search. Preferred Codec Auto-Selection

### ISSUE THREAD

**Issue by Kaito0** [ThaUnknown/miru#403]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Currently, manual searching is required to locate torrents with preferred codecs, leading to a less efficient user experience. 

### Proposed Solution

Implement a feature allowing users to search for torrents based on specific keywords or tags related to codecs (e.g., "h264," "aac") and/or Introduce an option for users to specify their preferred codec(s). The application would then automatically choose torrents that match those preferences.

**Comment by ThaUnknown** [comment]
this is a no for the same reason all other "filter torrent results" requests are denied: "this is too hard" 

first:
Miru's main focus is streaming, as such you need to prioritize torrents with enough seeders, which will allow real-time playback, this isn't qbit where you can wait 30hrs for a download to finish, and determining which torrent is suitable for streaming is insanely difficult, which is why Miru prioritizes seeders and torrents of high qualities which are permanently seeded, limiting the results it can pick from will pretty much always negatively impact it's viewing experience

second:
determining what codecs a torrent is, from the name alone isn't reliable, sometimes codecs are included, sometimes not

codecs rarely mean quality, there are cases where 264 will be better than 265 and other way around, thats why Miru picks what's best automatically from manually maintained databases

if you want to manually pick torrents then you can disable auto-pick torrents in settings, and filter the results to pick releases yourself, maybe a more appropriate issue would be "persist rss search filter"

you can also set a home screen rss feed which is of your preferred codec, from sources like ASW or erai-hevc
