### ISSUE TITLE
[Feature Request]: Ability to filter episodes by number

### ISSUE THREAD

**Issue by mdrokz** [ThaUnknown/miru#458]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

Right now for an anime that has more than 500 episodes such as detective conan it becomes very hard to go to the episode i want. For example if i wanted to go to a specific episode such as 531 i have to scroll all the way till i find it.

![image](https://github.com/ThaUnknown/miru/assets/33598169/f5ccb28d-b721-46b9-806a-e773ed496418)

### Proposed Solution

I propose we have search bar to filter the episodes by episode number or some way to go to specific episode

**Comment by ThaUnknown** [comment]
you're using an outdated version of miru

in later versions you can pick any episode which gives u a torrent picker popup, and you can change the episode number there, there are about 3 shows where this is an issue, and since i couldnt come up with a nice design for it i dont plan on implementing this
