### ISSUE TITLE
[Bug]: debian install

### ISSUE THREAD

**Issue by Laurent001** [ThaUnknown/miru#462]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

1.5.6

### What operating system version are you using?

Linux

### Expected Behavior

Install ok with command written in doc.

fix for Debian/Ubuntu :

```bash
chmod +x linux-Miru-*.deb
apt install ./linux-Miru-*.deb
```

### Actual Behavior

apt install try to search in repo the miru package. It does not find the package.

**Comment by ThaUnknown** [comment]
manage your permissions? this works correctly

miru isn't on any installer because that means maintaining it, i dont have the time, use official installs and auto-updater

**Comment by Laurent001** [comment]
I am not asking an installer 🙂
Just need to make a minor fix in the doc to make it easier to install with the .deb package.

If I execute : apt install <miru-package> (doc)
apt will try to go online and try to find the package and will not find it.

After downloaded the miru package, we need to make it exec (chmod +x) and launch install with apt like this : 
"apt install ./<deb package>"
instead of 
"apt install <deb package>"

I can make a MR if you prefer but I cannot because I have no permission to push.

Rgds

**Comment by Muril-o** [comment]
I see no need for the extra clarification that `linux-Miru-*.deb` is a file, as the description clearly says to download the file.
But since its an undocumented feature of apt (except for the [release changelog](https://mvogt.wordpress.com/2015/11/30/apt-1-1-released/), which doesn't even indicate the correct way of using it) maybe we could change the instructions
from
`apt install linux-Miru-*.deb`
to
`apt install /path/to/linux-Miru-*.deb`.

On a side note, is there a reason for the deb file to be executable? AFAIK you aren't running it, you're just passing the path to apt to handle it.

**Comment by Laurent001** [comment]
`maybe we could change the instructions
from
apt install linux-Miru-*.deb
to
apt install /path/to/linux-Miru-*.deb`

Sounds very good to me !
