### ISSUE TITLE
[Feature Request]: use a router for navigation

### ISSUE THREAD

**Issue by lv01-GreyCat** [ThaUnknown/miru#470]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description

When I'm browsing different pages on Miru; like 'New Releases', 'Popular This Season' or a search query. If I click on an episode, the previous context will be completely lost. I will have to type back the search term and scroll to where I was again for each new anime/episode I want to check out.

### Proposed Solution

I am not certain what would be the best design for this but maybe having a back button in the video player (+ escape hotkey, like how you can escape the 'Now Playing' page).  
I understand this might be difficult depending on how everything is handled. Hopefully my description has been clear enough.

**Comment by ThaUnknown** [comment]
yeah, the go-to solution for this is called a `router` which manages the paths you navigate to, issue is with the framework I'm using  I cannot use a good router because I need to use a very specific compiler to get the torrent tech behind Miru working correctly

**Comment by lv01-GreyCat** [comment]
It does not sound like an easy fix, that's a shame.  
When you say framework, are you talking about Svelte ?  
What is it that makes the compiler not allow the usage of a good router if you don't mind me asking ?

**Comment by ThaUnknown** [comment]
if you're curious I currently use Svelte with Webpack[bundler], I'm get to find a good router for normal Svelte, I'd like to use SvelteKit and it's router because it's actually fucking goated, but its Vite[bundler] only

the reason I need webpack is because of module aliasing and resolution, I need a bundler which can build multiple outputs in multiple different ways, for example:
- it needs to compile ESM to CJS as Electron doesn't support ESM
- it needs to compile for a custom enviorment which is both a browser and nodejs, that means it can both access the DOM and node.js API's
- it needs to compile for an environment which only implements some, but not all node.js api's [electron preload]
- it needs to compile for a normal website
- it needs to support module aliasing, aka "replace dependency X with dependency Y while compiling"

all in a single config in a single build. Vite can't do this

if you find a good router that can compare to sveltekit link it and I'll look at it
