### ISSUE TITLE
[Bug]: Some shows listed in the carousel don't open list of torrents/start playing and error out

### ISSUE THREAD

**Issue by kkarakk** [ThaUnknown/miru#474]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.1.10 Windows x64

### What operating system version are you using?

Windows

### Expected Behavior

Clicking "Watch Now" for a show in the carousel starts the show or depending on the user setting shows the list of torrents page for user to select

### Actual Behavior

Clicking "Watch Now" opens the list of torrents page and then closes it automatically and provides the error message 
"No torrent found for No Longer Allowed in
Another World Episode I!
No results found. Try specifying a torrent manually."

### Screenshots

![image](https://github.com/ThaUnknown/miru/assets/911913/86750943-c849-40c2-ba86-757abf36b145)

**Comment by ThaUnknown** [comment]
this should be fixed *for the most part*, as it's not actually possible to check if a torrent is available, tho you correctly pointed out that this carousel can show releases which haven't even aired yet, so this was fixed to only show anime which has already started airing, do note that that's not synonymous with "being available to watch on miru", since for example movies will be released on N day, but they will be available online after a few months, which Miru can't check
