### ISSUE TITLE
[Bug]: Crashes without warning

### ISSUE THREAD

**Issue by joshrg94** [ThaUnknown/miru#593]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

Can't use it long enough to check anymore, it should be the lastest version on the store

### What operating system version are you using?

Android

### Expected Behavior

The app works for more than 10 seconds.

### Actual Behavior

The app crashes quickly, the issue only started yesterday after months of using it, I once got it to go as far as opening a new video before it immediately crashed to home upon trying to start the download. Uninstalling and reinstalling allowed me to use the app but not actually watch anything, once I tried, the issue came back. I'm specifically using it on an androidTV, if that has any bearing to this.

**Comment by ThaUnknown** [comment]
is it one specific videos, or all videos in general?

**Comment by joshrg94** [comment]
I've tried 5 different series, including one I watched just a few days ago, so I assume it's for all.

**Comment by ThaUnknown** [comment]
yeah that indeed isn't normal, could I have the TV model ur using?

did it work fine previously?

**Comment by joshrg94** [comment]
I'm using an Onn 4k Streaming Box on a dumb tv, it's worked well since I got the app almost 2 months ago.

**Comment by ThaUnknown** [comment]
do you still have storage space on the device?

**Comment by ThaUnknown** [comment]
also could you go into android's app settings and clear cache and app data? what extensions are you using?

**Comment by joshrg94** [comment]
2.7gb, I had 2.1 when I started using the app, so I doubt that's it. I was hoping to be able to use external storage, but that never worked for me. Already cleared both and tried again before I tried a full reinstall. I'm just using anisearch.

**Comment by ThaUnknown** [comment]
hmmm, this is quite worrysome because it does not crash on any of my tvs or phones, and I doubt it leaves logs either if it full closes without an error popup.... I haven't updated the mobile app in months so I'm unsure what could have changed outside of your TV updating and breaking it's built in video player.... try finding an app called `WebView`, its a system app, and uninstalling its UPDATES, not the app do not remove the app! just uninstall updates [if possible], then try trying again

**Comment by joshrg94** [comment]
It displayed some really weird behavior at the start, but otherwise it worked like usual, thank you for the help. I'll have to keep that in mind if this issue ever returns.

**Comment by ThaUnknown** [comment]
great, so to summarize your device manufacturer pushed a faulty update, it's not something I can control unfortunately, but I'm happy uninstalling updates fixed it for you

**Comment by luma-inibitor** [comment]
Hi, I'm encountering the same issue with a different model of smart TV. I started encountering the issue around the same time as OP, so I think it's the same bad update, but it's been long enough now that I suspect it's worth looking into.

**Same issue:**
* Started happening for me in mid-November
* Not correlated with any Miru app releases
* Uninstalling updates from the Android System WebView app temporarily fixes it
* Not an issue with storage space
* Only extension is `anisearch`

**How it manifests:**
* Start the app
* Wait a few seconds
* Toast notification about previous torrent, attempts to resume
* Crash 15 seconds later
It's very consistent.

**Version stuff:**
App version v5.5.9 Android armv8l
Device: Smart TV 4K FFM
OS versions:
* Android TV OS version 11
* Android TV OS security patch level: August 1, 2024
* Kernel version: 4.19.182-ab571
* Android TV OS build: RTT2.211209.001

Android System WebView
* Working version: 99.0.4844.88 (factory reset version?)
* Busted version: 131.0.6778.135

---

I looked at the [changelog](https://support.google.com/product-documentation/answer/14343500?hl=en-GB#zippy=%2Cnovember) and it looks like Google released an update on Nov 6.

> Android WebView v131 (2024-11-06)
> * Improvements to security and privacy and updates for bug  
> * New developer features for Google and third-party app developers to support functionality related to displaying web content in their apps.
> Important: Some features may be experimental and available to certain users.

Thankfully since it's part of the Android project, we can see all the code and version history.
https://chromiumdash.appspot.com/releases?platform=Android
Unfortunately that's about as far as I can get without familiarizing myself with the code or pulling debug logs. Is there other info you'd like me to get that would help you figure this out? I have the feeling this isn't manufacturer-specific, but if you don't have time to dig deeper then any pointers would be appreciated for where I should look.
