### ISSUE TITLE
codec support

### ISSUE THREAD

**Issue by arynthernium** [ThaUnknown/miru#95]
Chromium does not have support for many common codecs, so eventually it would be useful to add support for those in-app. That should be doable by compiling a custom chromium build to add support and then compiling the electron application with that chromium build.

[This thread](https://stackoverflow.com/questions/43202554/compile-and-build-chromium-browser-for-electron) has information on compiling electron with custom chromium.
[This repo](https://github.com/henrypp/chromium) has information on compiling chromium with custom codecs.

**Comment by Muril-o** [comment]
A bit of update on this, I sucessfully compiled and built the electron [v16.1.0](https://github.com/electron/electron/releases/tag/v16.1.0) with chromium HEVC support on linux.
After some couple tries I couldn't reproduce it on windows due to external dependencies being a hassle to handle on windows itself. Here are a couple screenshots:

HEVC chromium html5 video test inside electron renderer
![image](https://user-images.githubusercontent.com/40826732/159005338-e93ddf2c-1956-4a23-9bf0-e084af3b7f88.png)

HEVC anime video being played on [miru](https://github.com/ThaUnknown/miru/releases/tag/v0.6.4)
![image](https://user-images.githubusercontent.com/40826732/159005348-a34d2f86-d7f7-462e-9952-a133eb6f898f.png)

Linux users should be able to download a release and have HEVC anime playing unlocked into [RSSView](https://github.com/ThaUnknown/miru/blob/master/src/renderer/src/lib/RSSView.svelte) very soon.
Will keep updated once I manage to reproduce a windows build and release an automated patch for future electron updates.

**Comment by ThaUnknown** [comment]
megabased

**Comment by ThaUnknown** [comment]
c723415b1aea792b4c241919ed14cf4dc3ad826b

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/miru/commit/26a1741aaecc3cea64c00569bb87d5f9bd94f05a
